(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["tuniao-ui/components/tn-avatar/tn-avatar"],{2772:function(t,e,n){"use strict";n.d(e,"b",(function(){return r})),n.d(e,"c",(function(){return i})),n.d(e,"a",(function(){return a}));var a={tnBadge:function(){return Promise.all([n.e("common/vendor"),n.e("tuniao-ui/components/tn-badge/tn-badge")]).then(n.bind(null,"7bdf"))}},r=function(){var t=this,e=t.$createElement,n=(t._self._c,t.__get_style([t.avatarStyle]));t.$mp.data=Object.assign({},{$root:{s0:n}})},i=[]},5514:function(t,e,n){"use strict";n.r(e);var a=n("2772"),r=n("d05b");for(var i in r)"default"!==i&&function(t){n.d(e,t,(function(){return r[t]}))}(i);n("d599");var o,u=n("f0c5"),d=Object(u["a"])(r["default"],a["b"],a["c"],!1,null,"f0e5da7c",null,!1,a["a"],o);e["default"]=d.exports},c31a:function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var a=r(n("93a6"));function r(t){return t&&t.__esModule?t:{default:t}}var i={mixins:[a.default],name:"tn-avatar",props:{index:{type:[Number,String],default:0},shape:{type:String,default:"circle"},size:{type:[Number,String],default:""},shadow:{type:Boolean,default:!1},border:{type:Boolean,default:!1},borderColor:{type:String,default:"rgba(0, 0, 0, 0.1)"},borderSize:{type:Number,default:2},src:{type:String,default:""},text:{type:String,default:""},icon:{type:String,default:""},imgMode:{type:String,default:"aspectFill"},badge:{type:Boolean,default:!1},badgeSize:{type:Number,default:0},badgeBgColor:{type:String,default:"#AAAAAA"},badgeColor:{type:String,default:"#FFFFFF"},badgeIcon:{type:String,default:""},badgeText:{type:String,default:""},badgePosition:{type:Array,default:function(){return[0,0]}}},data:function(){return{imgLoadError:!1}},computed:{showImg:function(){return""===this.text&&""===this.icon},avatarClass:function(){var t="";return t+=" tn-avatar--".concat(this.shape),this._checkSizeIsInline()&&(t+=" tn-avatar--".concat(this.size)),this.shadow&&(t+=" tn-avatar--shadow"),t},avatarStyle:function(){var t={};return this.backgroundColorStyle?t.background=this.backgroundColorStyle:this.shadow&&this.showImg&&(t.backgroundImage="url(".concat(this.src,")")),this.border&&(t.border="".concat(this.borderSize,"rpx solid ").concat(this.borderColor)),this._checkSizeIsInline()||(t.width=this.size,t.height=this.size),t},imgClass:function(){var t="";return t+=" tn-avatar__img--".concat(this.shape),t}},methods:{loadImageError:function(){this.imgLoadError=!0},click:function(){this.$emit("click",this.index)},_checkSizeIsInline:function(){return!!/^(xs|sm|md|lg|xl|xxl)$/.test(this.size)}}};e.default=i},d05b:function(t,e,n){"use strict";n.r(e);var a=n("c31a"),r=n.n(a);for(var i in a)"default"!==i&&function(t){n.d(e,t,(function(){return a[t]}))}(i);e["default"]=r.a},d599:function(t,e,n){"use strict";var a=n("de33"),r=n.n(a);r.a},de33:function(t,e,n){}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'tuniao-ui/components/tn-avatar/tn-avatar-create-component',
    {
        'tuniao-ui/components/tn-avatar/tn-avatar-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("5514"))
        })
    },
    [['tuniao-ui/components/tn-avatar/tn-avatar-create-component']]
]);
