(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["tuniao-ui/components/tn-switch/tn-switch"],{1280:function(t,e,n){"use strict";n.d(e,"b",(function(){return a})),n.d(e,"c",(function(){return o})),n.d(e,"a",(function(){return i}));var i={tnLoading:function(){return n.e("tuniao-ui/components/tn-loading/tn-loading").then(n.bind(null,"7a11"))}},a=function(){var t=this,e=t.$createElement,n=(t._self._c,t.__get_style([t.switchStyle])),i=t.__get_style([t.switchNodeStyle]),a=""!==t.leftIcon?t.__get_style([t.iconStyle]):null,o=""!==t.rightIcon?t.__get_style([t.iconStyle]):null;t.$mp.data=Object.assign({},{$root:{s0:n,s1:i,s2:a,s3:o}})},o=[]},4387:function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var n={name:"tn-switch",props:{value:{type:Boolean,default:!1},shape:{type:String,default:"circle"},disabled:{type:Boolean,default:!1},size:{type:Number,default:50},activeColor:{type:String,default:""},inactiveColor:{type:String,default:""},activeValue:{type:[Number,String,Boolean],default:!0},inactiveValue:{type:[Number,String,Boolean],default:!1},leftIcon:{type:String,default:""},rightIcon:{type:String,default:""},loading:{type:Boolean,default:!1},vibrateShort:{type:Boolean,default:!1}},computed:{switchStyle:function(){var t={};return t.fontSize=this.$t.string.getLengthUnitValue(this.size),t.backgroundColor=this.value?this.activeColor?this.activeColor:"#01BEFF":this.inactiveColor?this.inactiveColor:"#AAAAAA",t},switchNodeStyle:function(){var t={};return t.width=this.$t.string.getLengthUnitValue(this.size),t.height=t.width,t},iconStyle:function(){var t={};return t.fontSize=this.$t.string.getLengthUnitValue(this.size-20),t.lineHeight=this.$t.string.getLengthUnitValue(this.size),t},loadingColor:function(){return this.value?this.activeColor:""}},data:function(){return{}},methods:{click:function(){var e=this;this.disabled||this.loading||(this.vibrateShort&&t.vibrateShort(),this.$emit("input",!this.value),this.$nextTick((function(){e.$emit("change",e.value?e.activeValue:e.inactiveValue)})))}}};e.default=n}).call(this,n("543d")["default"])},8006:function(t,e,n){},b458:function(t,e,n){"use strict";n.r(e);var i=n("1280"),a=n("e623");for(var o in a)"default"!==o&&function(t){n.d(e,t,(function(){return a[t]}))}(o);n("bff4");var l,u=n("f0c5"),r=Object(u["a"])(a["default"],i["b"],i["c"],!1,null,"682d9a57",null,!1,i["a"],l);e["default"]=r.exports},bff4:function(t,e,n){"use strict";var i=n("8006"),a=n.n(i);a.a},e623:function(t,e,n){"use strict";n.r(e);var i=n("4387"),a=n.n(i);for(var o in i)"default"!==o&&function(t){n.d(e,t,(function(){return i[t]}))}(o);e["default"]=a.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'tuniao-ui/components/tn-switch/tn-switch-create-component',
    {
        'tuniao-ui/components/tn-switch/tn-switch-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("b458"))
        })
    },
    [['tuniao-ui/components/tn-switch/tn-switch-create-component']]
]);
