(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["tuniao-ui/components/tn-form/tn-form"],{"1ffa":function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var r={name:"tn-form",props:{model:{type:Object,default:function(){return{}}},errorType:{type:Array,default:function(){return["message","toast"]}},borderBottom:{type:Boolean,default:!0},labelPosition:{type:String,default:"left"},labelWidth:{type:Number,default:90},labelAlign:{type:String,default:"left"},labelStyle:{type:Object,default:function(){return{}}}},provide:function(){return{tnForm:this}},data:function(){return{rules:{}}},created:function(){this.fields=[]},methods:{setRules:function(t){this.rules=t},resetFields:function(){this.fields.map((function(t){t.resetField()}))},validate:function(t){var e=this;return new Promise((function(n){var r=!0,u=0,a=[];e.fields.map((function(o){o.validation("",(function(o){o&&(r=!1,a.push(o)),++u===e.fields.length&&(n(r),-1===e.errorType.indexOf("none")&&e.errorType.indexOf("toast")>=0&&a.length>0&&e.$t.messageUtils.toast(a[0]),"function"==typeof t&&t(r))}))}))}))}}};e.default=r},aed8:function(t,e,n){"use strict";n.r(e);var r=n("1ffa"),u=n.n(r);for(var a in r)"default"!==a&&function(t){n.d(e,t,(function(){return r[t]}))}(a);e["default"]=u.a},c6aa:function(t,e,n){"use strict";var r;n.d(e,"b",(function(){return u})),n.d(e,"c",(function(){return a})),n.d(e,"a",(function(){return r}));var u=function(){var t=this,e=t.$createElement;t._self._c},a=[]},e01a:function(t,e,n){"use strict";n.r(e);var r=n("c6aa"),u=n("aed8");for(var a in u)"default"!==a&&function(t){n.d(e,t,(function(){return u[t]}))}(a);var o,i=n("f0c5"),f=Object(i["a"])(u["default"],r["b"],r["c"],!1,null,null,null,!1,r["a"],o);e["default"]=f.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'tuniao-ui/components/tn-form/tn-form-create-component',
    {
        'tuniao-ui/components/tn-form/tn-form-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("e01a"))
        })
    },
    [['tuniao-ui/components/tn-form/tn-form-create-component']]
]);
