(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["tuniao-ui/components/tn-tag/tn-tag"],{"0e37":function(t,i,e){"use strict";var n;e.d(i,"b",(function(){return r})),e.d(i,"c",(function(){return a})),e.d(i,"a",(function(){return n}));var r=function(){var t=this,i=t.$createElement,e=(t._self._c,t.__get_style([t.tagStyle]));t.$mp.data=Object.assign({},{$root:{s0:e}})},a=[]},"45f1":function(t,i,e){"use strict";e.r(i);var n=e("f259"),r=e.n(n);for(var a in n)"default"!==a&&function(t){e.d(i,t,(function(){return n[t]}))}(a);i["default"]=r.a},"4cb8":function(t,i,e){"use strict";var n=e("a226"),r=e.n(n);r.a},a226:function(t,i,e){},a54d:function(t,i,e){"use strict";e.r(i);var n=e("0e37"),r=e("45f1");for(var a in r)"default"!==a&&function(t){e.d(i,t,(function(){return r[t]}))}(a);e("4cb8");var o,l=e("f0c5"),s=Object(l["a"])(r["default"],n["b"],n["c"],!1,null,"419de4ef",null,!1,n["a"],o);i["default"]=s.exports},f259:function(t,i,e){"use strict";Object.defineProperty(i,"__esModule",{value:!0}),i.default=void 0;var n=r(e("93a6"));function r(t){return t&&t.__esModule?t:{default:t}}var a={mixins:[n.default],name:"tn-tag",props:{index:{type:[Number,String],default:"0"},shape:{type:String,default:""},size:{type:String,default:""},width:{type:String,default:""},height:{type:String,default:""},padding:{type:String,default:""},margin:{type:String,default:"0"},plain:{type:Boolean,default:!1},originLeft:{type:Boolean,default:!1},originRight:{type:Boolean,default:!1}},computed:{tagClass:function(){var t="";switch(this.shape){case"radius":t+=" tn-radius";break;case"circle":t+=" tn-round";break;case"circleLeft":t+=" tn-tag--fillet-left";break;case"circleRight":t+=" tn-tag--fillet-right";break}if(this.plain&&(t+=" tn-tag--plain tn-border-solid",""!==this.backgroundColor&&this.backgroundColor.includes("tn-bg"))){var i=this.backgroundColor.slice(this.backgroundColor.lastIndexOf("-")+1);t+=" tn-border-".concat(i)}return this.originLeft&&(t+=" tn-tag--origin-left"),this.originRight&&(t+=" tn-tag--origin-right"),t},tagStyle:function(){var t={};switch(this.size){case"sm":t.padding="0 12rpx",t.fontSize="20rpx",t.height="32rpx";break;case"lg":t.padding="0 20rpx",t.fontSize="28rpx",t.height="62rpx";break;default:t.padding="0 16rpx",t.fontSize="24rpx",t.height="48rpx";break}return t.width=this.width||"120rpx",t.height=this.height||t.height,t.padding=this.padding||t.padding,this.margin&&(t.margin=this.margin),this.fontColorStyle&&(t.color=this.fontColorStyle),0!==this.fontSize&&(t.fontSize=this.fontSize+this.fontUnit),this.backgroundColorClass||(t.backgroundColor=this.plain?"":this.backgroundColorStyle||"#FFFFFF",this.plain&&(t.borderColor=this.backgroundColorStyle||"#080808")),t}},data:function(){return{}},methods:{handleClick:function(){this.$emit("click",{index:Number(this.index)}),this.$emit("tap",{index:Number(this.index)})}}};i.default=a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'tuniao-ui/components/tn-tag/tn-tag-create-component',
    {
        'tuniao-ui/components/tn-tag/tn-tag-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("a54d"))
        })
    },
    [['tuniao-ui/components/tn-tag/tn-tag-create-component']]
]);
