(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["tuniao-ui/components/tn-badge/tn-badge"],{"101c":function(t,e,n){"use strict";n.r(e);var i=n("dc44"),a=n.n(i);for(var r in i)"default"!==r&&function(t){n.d(e,t,(function(){return i[t]}))}(r);e["default"]=a.a},"65e1":function(t,e,n){"use strict";var i=n("a8f5"),a=n.n(i);a.a},"7bdf":function(t,e,n){"use strict";n.r(e);var i=n("e898"),a=n("101c");for(var r in a)"default"!==r&&function(t){n.d(e,t,(function(){return a[t]}))}(r);n("65e1");var u,o=n("f0c5"),d=Object(o["a"])(a["default"],i["b"],i["c"],!1,null,"01f439c1",null,!1,i["a"],u);e["default"]=d.exports},a8f5:function(t,e,n){},dc44:function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var i=a(n("93a6"));function a(t){return t&&t.__esModule?t:{default:t}}var r={mixins:[i.default],name:"tn-badge",props:{index:{type:[Number,String],default:"0"},radius:{type:Number,default:0},padding:{type:String,default:""},margin:{type:String,default:""},dot:{type:Boolean,default:!1},absolute:{type:Boolean,default:!1},top:{type:[String,Number],default:""},right:{type:[String,Number],default:""},translateCenter:{type:Boolean,default:!0}},computed:{badgeClass:function(){var t="";return this.dot&&(t+=" tn-badge--dot"),this.absolute&&(t+=" tn-badge--absolute",this.translateCenter&&(t+=" tn-badge--center-position")),t},badgeStyle:function(){var t={};return 0!==this.radius&&(t.width=this.radius+"rpx",t.height=this.radius+"rpx",t.lineHeight=this.radius+"rpx"),this.padding&&(t.padding=this.padding),this.margin&&(t.margin=this.margin),this.fontColorStyle&&(t.color=this.fontColorStyle),this.fontSize&&(t.fontSize=this.fontSize+this.fontUnit),this.backgroundColorStyle&&(t.backgroundColor=this.backgroundColorStyle),this.top&&(t.top=this.$t.string.getLengthUnitValue(this.top)),this.right&&(t.right=this.$t.string.getLengthUnitValue(this.right)),t}},data:function(){return{}},methods:{handleClick:function(){this.$emit("click",{index:Number(this.index)}),this.$emit("tap",{index:Number(this.index)})}}};e.default=r},e898:function(t,e,n){"use strict";var i;n.d(e,"b",(function(){return a})),n.d(e,"c",(function(){return r})),n.d(e,"a",(function(){return i}));var a=function(){var t=this,e=t.$createElement,n=(t._self._c,t.__get_style([t.badgeStyle]));t.$mp.data=Object.assign({},{$root:{s0:n}})},r=[]}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'tuniao-ui/components/tn-badge/tn-badge-create-component',
    {
        'tuniao-ui/components/tn-badge/tn-badge-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("7bdf"))
        })
    },
    [['tuniao-ui/components/tn-badge/tn-badge-create-component']]
]);
