(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["tuniao-ui/components/tn-modal/tn-modal"],{"0263":function(t,n,e){"use strict";var o=e("2fe5"),u=e.n(o);u.a},"0905":function(t,n,e){"use strict";Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var o=u(e("93a6"));function u(t){return t&&t.__esModule?t:{default:t}}var a={mixins:[o.default],name:"tn-modal",props:{value:{type:Boolean,default:!1},width:{type:String,default:"84%"},padding:{type:String,default:""},radius:{type:Number,default:12},title:{type:String,default:""},content:{type:String,default:""},button:{type:Array,default:function(){return[]}},safeAreaInsetBottom:{type:Boolean,default:!1},maskCloseable:{type:Boolean,default:!0},showCloseBtn:{type:Boolean,default:!1},zoom:{type:Boolean,default:!0},custom:{type:Boolean,default:!1},zIndex:{type:Number,default:0}},computed:{boxStyle:function(){var t={};return this.padding&&(t.padding=this.padding),this.backgroundColorStyle&&(t.backgroundColor=this.backgroundColorStyle),t},contentClass:function(){var t="";return this.title?t+=" tn-margin-top":t+=" tn-modal__box__content--no-title",t},contentStyle:function(){var t={};return this.fontSize&&(t.fontSize=this.fontSize+this.fontUnit),this.fontColorStyle&&(t.color=this.fontColorStyle),t}},data:function(){return{}},methods:{handleClick:function(t){this.value&&this.$emit("click",{index:Number(t)})},close:function(){this.$emit("cancel"),this.$emit("input",!1)}}};n.default=a},"2fe5":function(t,n,e){},ac8f:function(t,n,e){"use strict";e.r(n);var o=e("0905"),u=e.n(o);for(var a in o)"default"!==a&&function(t){e.d(n,t,(function(){return o[t]}))}(a);n["default"]=u.a},e112:function(t,n,e){"use strict";e.r(n);var o=e("fa61"),u=e("ac8f");for(var a in u)"default"!==a&&function(t){e.d(n,t,(function(){return u[t]}))}(a);e("0263");var i,l=e("f0c5"),r=Object(l["a"])(u["default"],o["b"],o["c"],!1,null,"5ebdff46",null,!1,o["a"],i);n["default"]=r.exports},fa61:function(t,n,e){"use strict";e.d(n,"b",(function(){return u})),e.d(n,"c",(function(){return a})),e.d(n,"a",(function(){return o}));var o={tnPopup:function(){return Promise.all([e.e("common/vendor"),e.e("tuniao-ui/components/tn-popup/tn-popup")]).then(e.bind(null,"b917"))},tnButton:function(){return Promise.all([e.e("common/vendor"),e.e("tuniao-ui/components/tn-button/tn-button")]).then(e.bind(null,"c442"))}},u=function(){var t=this,n=t.$createElement,e=(t._self._c,t.value?t.__get_style([t.boxStyle]):null);t.$mp.data=Object.assign({},{$root:{s0:e}})},a=[]}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'tuniao-ui/components/tn-modal/tn-modal-create-component',
    {
        'tuniao-ui/components/tn-modal/tn-modal-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("e112"))
        })
    },
    [['tuniao-ui/components/tn-modal/tn-modal-create-component']]
]);
