(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["tuniao-ui/components/tn-tips/tn-tips"],{"1e18":function(t,o,n){"use strict";var i;n.d(o,"b",(function(){return e})),n.d(o,"c",(function(){return s})),n.d(o,"a",(function(){return i}));var e=function(){var t=this,o=t.$createElement,n=(t._self._c,t.visibleSync?t.__get_style([t.tipsStyle]):null);t.$mp.data=Object.assign({},{$root:{s0:n}})},s=[]},"31f1":function(t,o,n){"use strict";var i=n("8b9a"),e=n.n(i);e.a},"7c4e":function(t,o,n){"use strict";n.r(o);var i=n("1e18"),e=n("b3a8");for(var s in e)"default"!==s&&function(t){n.d(o,t,(function(){return e[t]}))}(s);n("31f1");var r,l=n("f0c5"),u=Object(l["a"])(e["default"],i["b"],i["c"],!1,null,"4db6c95c",null,!1,i["a"],r);o["default"]=u.exports},"8b9a":function(t,o,n){},ac93:function(t,o,n){"use strict";Object.defineProperty(o,"__esModule",{value:!0}),o.default=void 0;var i={name:"tn-tips",props:{zIndex:{type:Number,default:0},position:{type:String,default:"top"},top:{type:Number,default:0}},computed:{tipsClass:function(){var t="";switch(this.position){case"top":t+=" tn-tips--top";break;case"center":t+=" tn-tips--center";break;case"bottom":t+=" tn-tips--bottom";break;default:t+=" tn-tips--top"}return this.showTips&&(t+=" tn-tips--show"),t},tipsStyle:function(){var t={};return"top"!==this.position&&""!==this.position||!this.top||(t.top=this.top+"px"),t.zIndex=(this.zIndex?this.zIndex:this.$t.zIndex.tips)+1,t},backgroundColorStyle:function(){return this.$t.colorUtils.getBackgroundColorStyle(this.backgroundColor)},backgroundColorClass:function(){return this.$t.colorUtils.getBackgroundColorInternalClass(this.backgroundColor)},fontColorStyle:function(){return this.$t.colorUtils.getFontColorStyle(this.fontColor)},fontColorClass:function(){return this.$t.colorUtils.getFontColorInternalClass(this.fontColor)}},data:function(){return{timer:null,visibleSync:!1,showTips:!1,msg:"",backgroundColor:"",fontColor:""}},methods:{show:function(){var t=this,o=arguments.length>0&&void 0!==arguments[0]?arguments[0]:{},n=o.duration,i=void 0===n?2e3:n,e=o.msg,s=void 0===e?"":e,r=o.backgroundColor,l=void 0===r?"":r,u=o.fontColor,c=void 0===u?"":u;if(null!==this.timer&&clearTimeout(this.timer),!s)return this._clearOptions(),void this.$emit("close");this.msg=s,this.backgroundColor=l||"#01BEFF",this.fontColor=c||"#FFFFFF",this.change("visibleSync","showTips",!0),this.timer=setTimeout((function(){clearTimeout(t.timer),t.timer=null,t.change("showTips","visibleSync",!1)}),i)},change:function(t,o,n){var i=this;this[t]=n,this.timer=n?setTimeout((function(){i[o]=n,i.$emit(n?"open":"close")}),50):setTimeout((function(){i[o]=n,i.$emit(n?"open":"close"),i._clearOptions()}),300)},_clearOptions:function(){this.msg="",this.backgroundColor="",this.fontColor=""}}};o.default=i},b3a8:function(t,o,n){"use strict";n.r(o);var i=n("ac93"),e=n.n(i);for(var s in i)"default"!==s&&function(t){n.d(o,t,(function(){return i[t]}))}(s);o["default"]=e.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'tuniao-ui/components/tn-tips/tn-tips-create-component',
    {
        'tuniao-ui/components/tn-tips/tn-tips-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("7c4e"))
        })
    },
    [['tuniao-ui/components/tn-tips/tn-tips-create-component']]
]);
