(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/common/copyright"],{"2b81":function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var r=n("2f62");function o(t,e){var n=Object.keys(t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(t);e&&(r=r.filter((function(e){return Object.getOwnPropertyDescriptor(t,e).enumerable}))),n.push.apply(n,r)}return n}function c(t){for(var e=1;e<arguments.length;e++){var n=null!=arguments[e]?arguments[e]:{};e%2?o(Object(n),!0).forEach((function(e){u(t,e,n[e])})):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(n)):o(Object(n)).forEach((function(e){Object.defineProperty(t,e,Object.getOwnPropertyDescriptor(n,e))}))}return t}function u(t,e,n){return e in t?Object.defineProperty(t,e,{value:n,enumerable:!0,configurable:!0,writable:!0}):t[e]=n,t}var a={name:"copyright",data:function(){return{color:"#777777",supportIcon:"https://static.xbsrj.cn/xbs_logo.png",supportInfo:"小帮手电商系统"}},computed:c({},(0,r.mapState)(["mpVersion","systemLogo","systemName","editionSetting"])),methods:{toSupport:function(){console.log("toSupport"),t.navigateToMiniProgram({appId:"wxcf244412a41b8001",path:"pages/index/index",extraData:{data1:"test"},success:function(t){console.log("success")}})}}};e.default=a}).call(this,n("543d")["default"])},5431:function(t,e,n){"use strict";var r=n("5e67"),o=n.n(r);o.a},"5e67":function(t,e,n){},"749f":function(t,e,n){"use strict";n.r(e);var r=n("ffdb"),o=n("d395");for(var c in o)"default"!==c&&function(t){n.d(e,t,(function(){return o[t]}))}(c);n("5431");var u,a=n("f0c5"),i=Object(a["a"])(o["default"],r["b"],r["c"],!1,null,null,null,!1,r["a"],u);e["default"]=i.exports},d395:function(t,e,n){"use strict";n.r(e);var r=n("2b81"),o=n.n(r);for(var c in r)"default"!==c&&function(t){n.d(e,t,(function(){return r[t]}))}(c);e["default"]=o.a},ffdb:function(t,e,n){"use strict";var r;n.d(e,"b",(function(){return o})),n.d(e,"c",(function(){return c})),n.d(e,"a",(function(){return r}));var o=function(){var t=this,e=t.$createElement;t._self._c},c=[]}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/common/copyright-create-component',
    {
        'components/common/copyright-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("749f"))
        })
    },
    [['components/common/copyright-create-component']]
]);
